// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_WebService.Models;
using AppContext = REST_WebService.Models.AppContext;

namespace REST_WebService.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REST_WebService.Models.Drawer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("Drawers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 10,
                            Length = 15,
                            Width = 30
                        },
                        new
                        {
                            Id = 2,
                            Height = 10,
                            Length = 15,
                            Width = 30
                        },
                        new
                        {
                            Id = 3,
                            Height = 10,
                            Length = 15,
                            Width = 30
                        },
                        new
                        {
                            Id = 4,
                            Height = 15,
                            Length = 15,
                            Width = 15
                        },
                        new
                        {
                            Id = 5,
                            Height = 40,
                            Length = 15,
                            Width = 10
                        });
                });

            modelBuilder.Entity("REST_WebService.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrawerId")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("LinkToSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DrawerId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = " an open-source microcontroller board based on the Microchip ATmega328P microcontroller and developed by Arduino.cc.",
                            Height = 5.2999999999999998,
                            Length = 1.2,
                            LinkToSite = "https://www.arduino.cc/",
                            Name = "Arduino UNO",
                            UnitCost = 16.00m,
                            Weight = 0.025000000000000001,
                            Width = 6.9000000000000004
                        });
                });

            modelBuilder.Entity("REST_WebService.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 15,
                            Length = 15,
                            Name = "Storage in Livingroom",
                            Width = 60
                        },
                        new
                        {
                            Id = 2,
                            Height = 60,
                            Length = 35,
                            Name = "hidden storage",
                            Width = 35
                        },
                        new
                        {
                            Id = 3,
                            Height = 120,
                            Length = 50,
                            Name = "Weapon storage",
                            Width = 220
                        });
                });

            modelBuilder.Entity("REST_WebService.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Arduino"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Board"
                        },
                        new
                        {
                            Id = 3,
                            Value = "5V"
                        },
                        new
                        {
                            Id = 4,
                            Value = "3.3V"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Beginners"
                        });
                });

            modelBuilder.Entity("REST_WebService.Models.Drawer", b =>
                {
                    b.HasOne("REST_WebService.Models.Storage", null)
                        .WithMany("DrawerList")
                        .HasForeignKey("StorageId");
                });

            modelBuilder.Entity("REST_WebService.Models.Item", b =>
                {
                    b.HasOne("REST_WebService.Models.Drawer", null)
                        .WithMany("Items")
                        .HasForeignKey("DrawerId");
                });

            modelBuilder.Entity("REST_WebService.Tag", b =>
                {
                    b.HasOne("REST_WebService.Models.Item", null)
                        .WithMany("TagList")
                        .HasForeignKey("ItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
